In [3]:
from sklearn.datasets import load_iris
iris=load_iris()
x=iris.data
y=iris.target
x,y

(array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5

In [7]:
feature_names=iris.feature_names
target_names=iris.target_names
print("feature name:",feature_names)
print("target name:",target_names)
print("first 10 rows of x:\n",x[:10])

feature name: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
target name: ['setosa' 'versicolor' 'virginica']
first 10 rows of x:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


In [10]:
print("first 2 rows of x:\n",x[2:10])

first 2 rows of x:
 [[4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


Splitting the dataset

In [14]:
from sklearn.datasets import load_iris
iris=load_iris()
x=iris.data
y=iris.target
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)


(105, 4)
(45, 4)
(105,)
(45,)


In [18]:
from sklearn.datasets import load_iris
iris=load_iris()
x=iris.data
y=iris.target
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=2,random_state=3)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(148, 4)
(2, 4)
(148,)
(2,)


Train the model

In [23]:
from sklearn.datasets import load_iris
iris=load_iris()
x=iris.data
y=iris.target
from sklearn.model_selection import train_test_split
x_train,x_Test,y_train,y_test=train_test_split(x,y,test_size=0.4,random_state=1)
from sklearn.neighbours import KNeighborsClassifier
from sklearn import metrics
classifier_knn=KNeighboursClassifier(n_neighbours=3)
classifier_knn.fit(x_train,y_train)
y_pred=classifier_knn.predict(x_test)
print("acuracy:",metrics.accuracy_score(y_test,y_pred))
sample=[[5,5,3,2],[2,4,3,5]]
preds=classifier_knn.predict(sample)
pred_species=[iris.target_names[p]for p in preds]
print("predictions:",pred_species)

ModuleNotFoundError: No module named 'sklearn.neighbours'

In [27]:
import numpy as np
from sklearn import preprocessing
input_data=np.array(
    [2.1,2.1,5.5],
    [-1.3,2.4,3.4],
    [0.5,-7.8,5.6],
    [5.6,2.3,5.8])
data_binarized=preprocessing.Binarizer(threashold=0.5).transform(input_data)
print("\nBinarized data:\n",data_binarized)

TypeError: data type not understood